<a href="https://colab.research.google.com/github/l0ngg/diveintocode/blob/master/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

for calculating the matrix product, i used two nested loop with 'i' and 'j' to loop through every position of the product matrix, with i being the row value and j being the column value

so for result matrix[0][0] it will be the sum of:


```
a[0][0]*b[0][0] + a[0][1]*b[1][0] + a[0][2]*b[2][0]
```

meaning we need to use a third looping number for this adition calculation
hence, in my code below, the multiplication is calculated using 3 nesting loops



In [5]:
#[Problem 1] Matrix product is calculated manually
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
result = np.array([[0,0,0],[0,0,0],[0,0,0]])

for i in range(3): #(row)
  for j in range(3): #(column)
    for k in range(3):
      result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]

print("matrix multiplication result: \n",result)

matrix multiplication result: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [10]:
#[Problem 2] Calculation by NumPy function
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("the product of matrix A and matrix B is:")
result = np.matmul(a_ndarray,b_ndarray)
print(result)

result = np.dot(a_ndarray, b_ndarray)
print(result)

result = a_ndarray@b_ndarray
print(result)

the product of matrix A and matrix B is:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [13]:
#[Problem 3] Implementation of calculation of a certain element
sum = 0

for i in range(3):
  sum += a_ndarray[0][i] + b_ndarray[i][0]

print("The result is: {}".format(sum))

The result is: 6


In [30]:
#[Problem 4] Creating a function that performs matrix multiplication
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def matrix_mul(a, b):
  aa_ndarray = a
  bb_ndarray = b

  #getting the required dimensions
  column_count = len(b[0])
  row_count = len(a)
  auxiliary = len(a[0])

  res = np.array([ [0]*column_count for i in range(row_count)])

  for i in range(row_count): #(row)
    for j in range(column_count): #(column)
      for k in range(auxiliary):
        res[i][j] += aa_ndarray[i][k] * bb_ndarray[k][j]
  return res

print("matrix multiplication result: \n",matrix_mul(a_ndarray, b_ndarray))

matrix multiplication result: 
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [36]:
#[Problem 5] Judge the input whose calculation is not defined
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


def matrix_mul2(a, b):
  aa_ndarray = a
  bb_ndarray = b

  #getting the required dimensions
  column_count = len(b[0])
  row_count = len(a)

  #check for undefined inputs
  column_a = len(a[0])
  row_b = len(b)

  if (column_a != row_b):
    print("The input matrixcies are not defined")
    return

  res = np.array([ [0]*column_count for i in range(row_count)])

  for i in range(row_count): #(row)
    for j in range(column_count): #(column)
      for k in range(row_b):
        res[i][j] += aa_ndarray[i][k] * bb_ndarray[k][j]
  return res


d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

matrix_mul2(d_ndarray, e_ndarray)

The input matrixcies are not defined


In [43]:
#[Problem 6] Transposition
print("result of tranposed d matrix multiply e matrix",matrix_mul2(d_ndarray.T, e_ndarray))
print("result of tranposed d multiply e tranposed matrix",matrix_mul2(d_ndarray, e_ndarray.T))

result of tranposed d matrix multiply e matrix [[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
result of tranposed d multiply e tranposed matrix [[ 46  -4]
 [-34  73]]
